### PR TITLE
Refresh index after manipulations with index via AerospikeTemplate

### PR DESCRIPTION
**Pull request by Aloren**

### CODE REVIEW

**Comment by Aloren** [comment]
@mzhangsfly could you please review? also can we have release version of spring-data-aerospike with this change? thanks

**Comment by mzhangsfly** [comment]
QueryEngine.refreshIndex method will send extensive Info command to all AS nodes and currently only add newly generated indexes to cache, but won't remove any.  In this case, the refreshIndex call within the delete index method may not perform as expected other than sending info command to the whole cluster.

**Comment by Aloren** [comment]
> refreshIndex method will send extensive Info command to all AS nodes

No, it sends info command only to the first available node:
https://github.com/aerospike/aerospike-client-java/blob/master/extensions/query-engine/src/main/java/com/aerospike/helper/query/QueryEngine.java#L672
There is a break statement in for loop that is not very obvious at the first glance.

> In this case, the refreshIndex call within the delete index method may not perform as expected

delete operation requires changes in `QueryEngine`. i've started updating the code in `QueryEngine`, but have not created PR yet. i can remove `refreshIndex` on delete operation in this PR and add it back separately after update in `QueryEngine`. wdyt?

**Comment by mzhangsfly** [comment]
> > refreshIndex method will send extensive Info command to all AS nodes
> 
> No, it sends info command only to the first available node:
> https://github.com/aerospike/aerospike-client-java/blob/master/extensions/query-engine/src/main/java/com/aerospike/helper/query/QueryEngine.java#L672
> There is a break statement in for loop that is not very obvious at the first glance.
> 

You are right.

> > In this case, the refreshIndex call within the delete index method may not perform as expected
> 
> delete operation requires changes in `QueryEngine`. i've started updating the code in `QueryEngine`, but have not created PR yet. i can remove `refreshIndex` on delete operation in this PR and add it back separately after update in `QueryEngine`. wdyt?

I think you can leave it there for now.  From behavior point of view, this refresh is now forced for each index operation(add/delete).

Agree that QueryEngine will need some tune-up, especially this cache is a TreeMap which could be dirty in multi thread environment.

We can release together with your QueryEngine update.

**Pull request merged**
